# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.cache/wt [current_project]
set_property parent.project_path E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0327-0230
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0325-0030
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0324-1715
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0324-0500
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0324-0300
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0323-2000
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0322-1900
} [current_project]
set_property ip_output_repo e:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.srcs/sources_1/new/axi_m_mem.v
  E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.srcs/sources_1/new/rgb444_diff.v
  E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.srcs/sources_1/new/IPU_top.v
}
read_ip -quiet E:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/main/IPU_v2.0/IPU_v2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top IPU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef IPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file IPU_utilization_synth.rpt -pb IPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
