# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_IPU_0_0/vi_sys_IPU_0_0.xci
# IP: The module: 'vi_sys_IPU_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_IPU_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_IPU_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_IPU_0_0/vi_sys_IPU_0_0.xci
# IP: The module: 'vi_sys_IPU_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_IPU_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_IPU_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
