# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_xbar_1/vi_sys_xbar_1.xci
# IP: The module: 'vi_sys_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_xbar_1/vi_sys_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vi_sys_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_xbar_1/vi_sys_xbar_1.xci
# IP: The module: 'vi_sys_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_xbar_1/vi_sys_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vi_sys_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
