# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vi_sys_constraints.xdc

# Block Designs: bd/vi_sys/vi_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys || ORIG_REF_NAME==vi_sys} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_microblaze_0_0/vi_sys_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_microblaze_0_0 || ORIG_REF_NAME==vi_sys_microblaze_0_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_microblaze_0_axi_periph_0/vi_sys_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==vi_sys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_microblaze_0_axi_intc_0/vi_sys_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==vi_sys_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_microblaze_0_xlconcat_0/vi_sys_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==vi_sys_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_mdm_1_0/vi_sys_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_mdm_1_0 || ORIG_REF_NAME==vi_sys_mdm_1_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_clk_wiz_1_0/vi_sys_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_clk_wiz_1_0 || ORIG_REF_NAME==vi_sys_clk_wiz_1_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_rst_clk_wiz_1_100M_0/vi_sys_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==vi_sys_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_axi_uartlite_0_0/vi_sys_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_axi_uartlite_0_0 || ORIG_REF_NAME==vi_sys_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_xbar_0/vi_sys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_xbar_0 || ORIG_REF_NAME==vi_sys_xbar_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_dlmb_v10_0/vi_sys_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_dlmb_v10_0 || ORIG_REF_NAME==vi_sys_dlmb_v10_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_ilmb_v10_0/vi_sys_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_ilmb_v10_0 || ORIG_REF_NAME==vi_sys_ilmb_v10_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_dlmb_bram_if_cntlr_0/vi_sys_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==vi_sys_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_ilmb_bram_if_cntlr_0/vi_sys_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==vi_sys_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_lmb_bram_0/vi_sys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_lmb_bram_0 || ORIG_REF_NAME==vi_sys_lmb_bram_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_axi_bram_ctrl_0_0/vi_sys_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==vi_sys_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_blk_mem_gen_0_0/vi_sys_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_blk_mem_gen_0_0 || ORIG_REF_NAME==vi_sys_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_axi_interconnect_0_0/vi_sys_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_axi_interconnect_0_0 || ORIG_REF_NAME==vi_sys_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_IPU_0_0/vi_sys_IPU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_IPU_0_0 || ORIG_REF_NAME==vi_sys_IPU_0_0} -quiet] -quiet

# IP: bd/vi_sys/ip/vi_sys_xbar_1/vi_sys_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vi_sys_xbar_1 || ORIG_REF_NAME==vi_sys_xbar_1} -quiet] -quiet

# XDC: bd/vi_sys/vi_sys_ooc.xdc
