# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.cache/wt [current_project]
set_property parent.project_path E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0324-1715
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0327-2300
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0327-0230
  e:/ECE532/WorkSpace/IPU_proj/Packaged/0325-0030
} [current_project]
set_property ip_output_repo e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/hdl/vi_sys_wrapper.v
add_files E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/vi_sys.bd
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_microblaze_0_0/vi_sys_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_microblaze_0_0/vi_sys_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_microblaze_0_0/vi_sys_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_microblaze_0_axi_intc_0/vi_sys_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_microblaze_0_axi_intc_0/vi_sys_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_microblaze_0_axi_intc_0/vi_sys_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_mdm_1_0/vi_sys_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_mdm_1_0/vi_sys_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_clk_wiz_1_0/vi_sys_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_clk_wiz_1_0/vi_sys_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_clk_wiz_1_0/vi_sys_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_rst_clk_wiz_1_100M_0/vi_sys_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_rst_clk_wiz_1_100M_0/vi_sys_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_rst_clk_wiz_1_100M_0/vi_sys_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_axi_uartlite_0_0/vi_sys_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_axi_uartlite_0_0/vi_sys_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_axi_uartlite_0_0/vi_sys_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_xbar_0/vi_sys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_dlmb_v10_0/vi_sys_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_dlmb_v10_0/vi_sys_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_ilmb_v10_0/vi_sys_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_ilmb_v10_0/vi_sys_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_dlmb_bram_if_cntlr_0/vi_sys_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_ilmb_bram_if_cntlr_0/vi_sys_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_lmb_bram_0/vi_sys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_axi_bram_ctrl_0_0/vi_sys_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_blk_mem_gen_0_0/vi_sys_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_IPU_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/ip/vi_sys_xbar_1/vi_sys_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/sources_1/bd/vi_sys/vi_sys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/constrs_1/new/vi_sys_constraints.xdc
set_property used_in_implementation false [get_files E:/ECE532/WorkSpace/IPU_proj/Verification/MB_Validation/MB_Validation.srcs/constrs_1/new/vi_sys_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top vi_sys_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vi_sys_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vi_sys_wrapper_utilization_synth.rpt -pb vi_sys_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
