webtalk_init -webtalk_dir E:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/proj_p3.sim/sim_1/behav/xsim/xsim.dir/part3_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 27 03:05:49 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174111048_179741397_210699440_801" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "33a758ff8a8e557d9a9cfe5dcfd085fb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9e670d851153486a986cc967ad313073" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.44_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "20240_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1337946179 -regid "174111048_179741397_210699440_801" -xml E:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/proj_p3.sim/sim_1/behav/xsim/xsim.dir/part3_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/proj_p3.sim/sim_1/behav/xsim/xsim.dir/part3_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/ECE532/WorkSpace/IPU_proj/Verification/tb_proj/proj_p3.sim/sim_1/behav/xsim/xsim.dir/part3_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
